import Providers from "@/app/Providers";
import "../globals.css";
import { ReactNode } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface LayoutProps {
  children: ReactNode;
}

export default function uLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
